#!/bin/sh
# X11 read this file in startup

# Load and merge the resources file
[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources

mons -s
xcalib ~/.config/icc/xps9500fhd.icm
xsettingsd &
libinput-gestures-setup restart
brillo -I
sudo intel-undervolt apply
sudo intel_gpu_frequency -i
sudo pstate-frequency -S -m 72
sudo mount /dev/nvme1n1p1 /mnt/luna
wmname LG3D
xset s off -dpms
xsetroot -cursor_name left_ptr
#setbg
#wallpaperService &
#hsetroot -solid "#3d3f51"
#xsetroot -bitmap ~/.local/share/backgrounds/bitmap-walls/bw-bgnd/cyber_tile.xbm -bg "#191724" -fg "#3d3f51"
#hsetroot -tile ~/.local/share/backgrounds/tilingGengar2.png
#nautilus --gapplication-service
#pipewire &
udiskie &
picomSwitch &
numlockx &
#hhpc -i 4 &
plank &
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK
pipewire &
#sudo intel-undervolt apply
exec awesome
